spring.application.name=price-service
# JPA / Hibernate
spring.datasource.url=jdbc:h2:mem:pricedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=./target/db/schema.sql
#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata