CREATE TABLE prices
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid         VARCHAR(36)                 NOT NULL UNIQUE,
    amount       NUMERIC(38, 2)              NOT NULL,
    currency     VARCHAR(3)                  NOT NULL,
    priority     INTEGER                     NOT NULL,
    brand_uuid   VARCHAR(36)                 NOT NULL,
    product_uuid VARCHAR(36)                 NOT NULL,
    start_date   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_date     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_date TIMESTAMP(6)                NOT NULL,
    updated_date TIMESTAMP(6)                NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_prices_optimized
    ON prices (start_date, end_date, brand_uuid, product_uuid, priority DESC);