CREATE TABLE brands
(
    created_date TIMESTAMP(6) NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_date TIMESTAMP(6) NOT NULL,
    name         VARCHAR(20)  NOT NULL,
    uuid         VARCHAR(36)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
);
CREATE TABLE products
(
    created_date TIMESTAMP(6) NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_date TIMESTAMP(6) NOT NULL,
    name         VARCHAR(100) NOT NULL,
    code         VARCHAR(20)  NOT NULL,
    description  VARCHAR(150) NOT NULL,
    uuid         VARCHAR(36)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
);
CREATE TABLE prices
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid         VARCHAR(36)                 NOT NULL UNIQUE,
    amount       NUMERIC(38, 2)              NOT NULL,
    currency     VARCHAR(3)                  NOT NULL,
    priority     INTEGER                     NOT NULL,
    brand_id     BIGINT                      NOT NULL,
    product_id   BIGINT                      NOT NULL,
    start_date   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_date     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_date TIMESTAMP(6)                NOT NULL,
    updated_date TIMESTAMP(6)                NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE prices
    ADD CONSTRAINT fk_prices_brand FOREIGN KEY (brand_id) REFERENCES brands (id);

ALTER TABLE prices
    ADD CONSTRAINT fk_prices_product FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX idx_prices_optimized
    ON prices (start_date, end_date, brand_id, product_id, priority DESC);